SRC	 = RMI_init.java
SRC	+= i_Data.java
SRC	+= i_Reduce.java
SRC	+= i_BroadcastObject.java
SRC	+= Data.java
SRC	+= Reduce.java
SRC	+= BroadcastObject.java
SRC	+= BroadcastSender.java
SRC	+= PivotElt.java
SRC	+= QR_PIVOT_IX_T.java
SRC	+= QR_Pivot.java

MAIN	+= Main.java

REMOTE	 = Data.java
REMOTE	+= Reduce.java
REMOTE	+= BroadcastObject.java

SERIALIZABLE  = PivotElt.java

include ../../../config.mk

clean:
	rm -f $(TRASH_FILES) rmi_s*_Data.java rmi_s*_Reduce.java rmi_s*_BroadcastObject.java
