SRC	=
SRC	+= StoreOutputStream.java
SRC	+= StoreInputStream.java
SRC	+= StoreBuffer.java
SRC	+= List.java

MAIN = Main.java

SERIALIZABLE =
SERIALIZABLE += List.java

include ../../../../../config.mk

clean:
	rm -f $(TRASH_FILES)
