APP_OPTIONS = pics/balls2.nff

OUT= raytracer

include ../../../config.mk
include ../config.mk

java:
	$(JAVAC_COMMAND) Raytracer.java

satin: 
	$(IBISC_COMMAND) Raytracer.java

clean:
	rm -f $(TRASH_FILES)

include ../run.mk
