APP_OPTIONS = pics/balls2_hires.nff

OUT= raytracer

MAIN=Raytracer.java

include ../../../config.mk
include ../config.mk

satin: 
	$(IBISC_COMMAND) -no-aborts $(MAIN)

clean:
	rm -f $(TRASH_FILES)

include ../run.mk
