#! /bin/sh

case X$JAVA_HOME in
X)
    echo The enviroment variable JAVA_HOME must be set to the current jdk 1>&2
    echo distribution installed on your computer, which must be a 1.4 version 1>&2
    echo or newer. 1>&2
    exit 1
    ;;
esac

3rdparty/apache-ant-1.6.1/bin/ant "$@"
