SRC  =
SRC += myServer.java 
SRC += Data.java
SRC += List.java
SRC += DList.java
SRC += Tree.java

MAIN = Main.java
OUT=main

REMOTE	=
REMOTE	+= Test.java

include ../../../config.mk

manta: $(MAIN) $(O_FILES)
#	$(MANTAC_COMMAND) -o $(OUT) $(MAIN) $(O_FILES) ../../../../ibis/$(IBIS_LIB)

clean:
	rm -f $(TRASH_FILES) rmi_s*_Test.java







