SRC  = myServer.java 
SRC += Data.java
SRC += List.java
SRC += DList.java
SRC += Tree.java
SRC += Test.java

MAIN  = Main.java

REMOTE  = Test.java

SERIALIZABLE  = Data.java
SERIALIZABLE  += Tree.java
SERIALIZABLE  += List.java
SERIALIZABLE  += DList.java

include ../../../config.mk

clean:
	rm -f $(TRASH_FILES) rmi_s*_Test.java
