#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

case X$IBIS_ROOT in
X)
    IBIS_ROOT=`cd "$dir/.." && pwd`
    ;;
esac

export IBIS_ROOT

JAVACLASSPATH="$CLASSPATH:$IBIS_ROOT/3rdparty/ibis-util.jar:"

case X$JAVA_ROOT in
X)
    JAVA=java
    ;;
*)
    JAVA="$JAVA_ROOT/bin/java"
    ;;
esac

"$JAVA" -classpath "$JAVACLASSPATH" ibis.util.PoolInfoServer "$@"
