#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

case X$IBIS_ROOT in
X)
    IBIS_ROOT=`cd "$dir/.." && pwd`
    ;;
esac

export IBIS_ROOT

if [ -z "$JAVA_HOME" ]
then
    if [ -z "$JAVA_ROOT" ]
    then
	echo "ibis-ant: either the JAVA_HOME or the JAVA_ROOT environment variable must be set" 1>&2
	exit 1
    fi
    JAVA_HOME="$JAVA_ROOT"
fi

export JAVA_HOME

ant "$@"
