#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. "$dir"/../configuration.sh

export IBIS_ROOT
if [ ! -z "$JAVA_HOME" ]
then	:
else 
    JAVA_HOME=$JAVA_ROOT
fi
export JAVA_HOME

ant "$@"
