#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. "$dir"/../configuration.sh

# javap with classpath

JAVACLASSPATH="$CLASSPATH:$IBIS_ROOT/classlibs:$IBIS_ROOT/lib/ibis.jar:build:$BCEL:.:"

"$JAVA_ROOT"/bin/javap -classpath "$JAVACLASSPATH" -bootclasspath "$JAVACLASSPATH" "$@"
