#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. $dir/../configuration.sh

JAVACLASSPATH=build:.:$IBIS_ROOT/classlibs:$IBIS_ROOT/lib/ibis.jar

export LD_ASSUME_KERNEL=2.2.5

#disable panda interrupte
#export IBP_NO_INTR=1

# fix panda/lfc flow control
#export LFC_SEND_COPY_ASIDE=1
#export PAN_SYS_CREDITS=65535

export LFC_INTR_FIRST=100
export IBP_SEND_SYNC=100 
export MANTA_NO_PANDA=1
export PAN_COMM_NO_IDLE_POLL=1

Dlibpath="-Dsun.boot.library.path=$IBIS_ROOT/lib/natives:$JAVA_ROOT/jre/bin:$JAVA_ROOT/jre/lib/i386"

Dpool_host_num="-Dibis.pool.host_number=$1"
shift

#Dpool_total="-Dibis.pool.total_hosts=$1"
shift

if [ -z "$PRUN_ENV" ]
then
    Dns_pool="-Dibis.name_server.key=$1"
    shift
else
    Dns_pool="-Dibis.name_server.key=$PRUN_ENV"
fi

case $1 in
[0-9]*)
    # "old" syntax: <portno> <nameserver-host>
    Dns_port="-Dibis.name_server.port=$1"
    shift
    Dns_server="-Dibis.name_server.host=$1"
    shift
    ;;
*:*)
    # "new" syntax: <nameserver-host>:<portno>
    Dns_port="-Dibis.name_server.port="`expr "$1" : '.*:\(.*\)'`
    Dns_server="-Dibis.name_server.host="`expr "$1" : '\(.*\):.*'`
    shift
    ;;
*)
    # assume <nameserver-host> and default port
    Dns_port=
    Dns_server="-Dibis.name_server.host=$1"
    shift
    ;;
esac

Dpool_total="-Dibis.pool.total_hosts=$1"
shift

$JAVA_ROOT/bin/java $Dlibpath $Dpool_host_num $Dpool_total $Dns_pool $Dns_port $Dns_server -Xmx1024M -Xbootclasspath/p:$JAVACLASSPATH -classpath $JAVACLASSPATH: "$@"
