#!/bin/sh

#APP=Fib
#PROBLEMSIZE=40
RUNSIZE=32
POOL=bla
NAMESERVER=flits.cs.vu.nl
NAMESERVER_PORT=5432

#NAMESERVER=origin.aei-potsdam.mpg.de
#NAMESERVER_PORT=7600

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=0 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=1 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=2 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=3 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=4 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=5 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=6 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=7 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=8 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=9 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=10 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=11 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=12 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=13 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=14 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &

/usr/java/bin/java -native -Xmx400M -Dfirewall_range=7000-8000 -Dibis.pool.host_number=15 -Dibis.pool.total_hosts=$RUNSIZE -Dibis.name_server.key=$POOL -Dibis.name_server.host=$NAMESERVER -Dibis.name_server.port=$NAMESERVER_PORT -Dibis.property.file=$HOME/projects/ibis/properties -classpath $HOME/projects:. $1 $2 -satin-closed -satin-stats -satin-ibis &
