package ibis.satin;

/** 
 * A super class for all parameter records generated by Satinc;
 * Used in the implementation of the Global Result Table
 */
public class ParameterRecord implements java.io.Serializable {
//    public abstract String toString();
};