/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_io_JavaMx */

#ifndef _Included_ibis_ipl_impl_mx_io_JavaMx
#define _Included_ibis_ipl_impl_mx_io_JavaMx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1init
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_openEndpoint
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1openEndpoint
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_getMyNicID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1getMyNicID
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_getMyEndpointId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1getMyEndpointId
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_getNicID
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1getNicID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_connect
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1connect
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_finalize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1finalize
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_send
 * Signature: (Ljava/nio/ByteBuffer;IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1send__Ljava_nio_ByteBuffer_2IJ
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_send
 * Signature: ([BIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1send___3BIJ
  (JNIEnv *, jclass, jbyteArray, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_asend
 * Signature: (Ljava/nio/ByteBuffer;IJ)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1asend
  (JNIEnv *, jclass, jobject, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_recv
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1recv__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_recv
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1recv__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_arecv
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1arecv
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_wait
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1wait
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_io_JavaMx
 * Method:    jmx_test
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_io_JavaMx_jmx_1test
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
