#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. "$dir"/../configuration.sh

mycpu=$PRUN_CPU_RANK
host_array=($HOSTS)
ncpus=${#host_array[@]}

nclusters=0
cpu=1

ACT=eval

for i
do
	# We do an eval. Carefullly quote arguments in case they contain
	# spaces.
	qarg="'"$i"'"

	case $i in

	-cluster=*)
		nclusters=`expr $i : '-cluster=\(.*\)'`
		;;
	-cl=*)
		nclusters=`expr $i : '-cl=\(.*\)'`
		;;

	-spin=*)
		export PAN_CLUSTER_SPIN=`expr $i : '-spin=\(.*\)'`
		;;

	-thrp=*)
		export PAN_CLUSTER_THRP=`expr $i : '-thrp=\(.*\)'`
		;;

	-cpu)
		cpu=`expr $i : '-cpu=\(.*\)'`
		;;

	-n)
		ACT=echo
		;;

	*)
		ARGS="$ARGS $qarg"
		;;
	esac
done

export CLASSPATH="$IBIS_ROOT/build:"
export LD_LIBRARY_PATH="$IBIS_ROOT/build/lib:"

# export PAN_COMM_NO_INTR=1
export PAN_COMM_NO_IDLE_POLL=1

if [ $nclusters -gt 0 ]
then
	export PAN_CLD=$nclusters
fi

export MANTA_NO_PANDA=1

export IBP_SEND_SYNC=100
# export IBP_NO_INTR=1

export LFC_RECV_PKTS=1024

# echo mycpu $mycpu ncpus $ncpus nclusters $nclusters

if (( $mycpu < $ncpus - $nclusters ))
then
	i=`expr $ncpus - $nclusters`
	while [ $i -lt $ncpus ]
	do
		echo Now unset host_array $i
		unset host_array[$i]
		i=`expr $i + 1`
	done
	# echo host_array = ${host_array[@]}
	hosts="'"${host_array[@]}"'"
	$ACT "$IBIS_ROOT"/bin/java_wrapper \
		"$JAVA_ROOT"/bin/java \
		-Xmx400M -Xcomp \
		-Djava.library.path="$IBIS_ROOT/build/lib" \
		-Dibis.pool.host_names="$hosts" \
		-Dibis.pool.total_hosts="${#host_array[@]}" \
		-Dibis.pool.host_number=$PRUN_CPU_RANK \
		-Dibis.name_server.host=$NS_HOSTNAME \
		-Dibis.name_server.key=rutger$PRUN_ENV \
		-Dibis.name_server.port=7654 \
		$ARGS
else
	# echo "I am cluster coordinator, it seems; PRUN_CPU_RANK $PRUN_CPU_RANK"
	"$IBIS_ROOT"/bin/java_wrapper \
		"$JAVA_ROOT"/bin/java \
		-Xmx400M -Xcomp \
		-Djava.library.path="$IBIS_ROOT/build/lib" \
		ibis.impl.messagePassing.PandaIbis
fi
