#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. $dir/../configuration.sh

echo $*

#used for running tcp-ibis with different -Dcluster settings
RANK=$1
TOTAL_NODES=$2
NODES_PER_CLUSTER=$3
DNAMESERVER="-Dibis.name_server.key=$4 -Dibis.name_server.port=$5 -Dibis.name_server.host=$6"
shift 6

CLUSTERID=$(($RANK / $NODES_PER_CLUSTER))

$JAVA_ROOT/bin/java -Xmx400M -Dibis.pool.host_number=$RANK -Dibis.pool.total_hosts=$TOTAL_NODES -Dcluster=$CLUSTERID $DNAMESERVER "$@"

