#!/bin/sh

PRG="$0"

# resolve symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
done

dir=`dirname "$PRG"`
dir=`cd "$dir" && pwd`

. $dir/../configuration.sh

#used for running ibis with the panda cluster simulator
RANK=$1
NODES_INCL_GATEWAYS=$2
CLUSTERS=$3
shift 3

#read the layout parameters, one for each cluster
LAYOUT=
for i in `seq 1 $CLUSTERS`; do
	LAYOUT="$LAYOUT $(($1-1))" #remove the gateways from the layout
	shift
done

declare -i FOO=$RANK
declare -i CLUSTERID=0
for i in $LAYOUT; do
	if [ $FOO -lt $i ]; then
		#found my cluster
		break
	else
		FOO=$FOO-$i
		CLUSTERID=$CLUSTERID+1		
	fi
done

NODES_EXCL_GATEWAYS=$(( $NODES_INCL_GATEWAYS-$CLUSTERS ))

#if [ -z "$PAN_CLD" ]; then
#	PAN_CLD=0
#fi

if [ $RANK -ge $NODES_EXCL_GATEWAYS ]; then
	export LFC_RECV_PKTS=1024
	$JAVA_ROOT/bin/java ibis.impl.messagePassing.PandaIbis
else
	echo csim_run_ibis: My clusterid is.. clust$CLUSTERID
	$JAVA_ROOT/bin/java -Xmx400M -Dibis.pool.host_number=$RANK -Dibis.pool.total_hosts=$NODES_EXCL_GATEWAYS -Dcluster=clust$CLUSTERID "$@"
#-Xrunhprof:cpu=samples,file=log$NODES_EXCL_GATEWAYS-$RANK.txt "$@"
fi
