SRC	+= Constraints.java
SRC	+= Data.java
SRC	+= Input.java
SRC	+= Matrix.java
SRC	+= Monitor.java
SRC	+= NoSolutionException.java
SRC	+= OrcaRandom.java
SRC	+= RMI_init.java
SRC	+= Relation.java
SRC	+= Work.java
SRC	+= i_Data.java
SRC	+= i_Matrix.java
SRC	+= i_Work.java

MAIN	 = ACP.java

REMOTE	 = Matrix.java
REMOTE	+= Data.java
REMOTE	+= Work.java

SERIALIZABLE  = Constraints.java
SERIALIZABLE += Relation.java

include ../../../config.mk

clean:
	rm -rf $(TRASH_FILES) rmi_s*_Matrix.java rmi_s*_Data.java rmi_s*_Work.java
