clean:
	cd seq; make clean
	cd par; make clean
	cd par_flat_tt; make clean
	cd par_flat_tt_repl; make clean
	cd par_flat_tt_repl_sockets; make clean
	cd par_prealloc; make clean

distclean:
	cd seq; make distclean
	cd par; make distclean
	cd par_flat_tt; make distclean
	cd par_flat_tt_repl; make distclean
	cd par_flat_tt_repl_sockets; make distclean
	cd par_prealloc; make distclean
