APP_OPTIONS =
TEST_APP_OPTIONS =

MAIN = TwoOutThree.java
OUT= two_out_three

include ../../../config.mk
include ../config.mk

satin:
	$(IBISC_COMMAND) $(MAIN)

clean:
	rm -f $(TRASH_FILES) test_out test_err test_res

include ../run.mk
