include ../../../config.mk

java: 
	cd array; $(MAKE) $(MFLAGS) java
	cd array-sun; $(MAKE) $(MFLAGS) java	
	cd array-writeArray; $(MAKE) $(MFLAGS) java	
	cd array-conv; $(MAKE) $(MFLAGS) java
	cd array-conv-writeArray; $(MAKE) $(MFLAGS) java
	cd list-final; $(MAKE) $(MFLAGS) java
	cd list-final-conv; $(MAKE) $(MFLAGS) java
	cd list-normal; $(MAKE) $(MFLAGS) java
	cd list-normal-conv; $(MAKE) $(MFLAGS) java
	cd tree-final; $(MAKE) $(MFLAGS) java
	cd tree-final-conv; $(MAKE) $(MFLAGS) java
	cd tree-final-sun; $(MAKE) $(MFLAGS) java
	cd object-array; $(MAKE) $(MFLAGS) java	
	cd object-array-conv; $(MAKE) $(MFLAGS) java
	cd int-array; $(MAKE) $(MFLAGS) java	
	cd int-array-conv; $(MAKE) $(MFLAGS) java
	cd dlist-final; $(MAKE) $(MFLAGS) java
	cd dlist-final-conv; $(MAKE) $(MFLAGS) java

manta:
	cd array; $(MAKE) $(MFLAGS) manta	
	cd array-sun; $(MAKE) $(MFLAGS) manta	
	cd array-writeArray; $(MAKE) $(MFLAGS) manta	
	cd array-conv; $(MAKE) $(MFLAGS) manta
	cd array-conv-writeArray; $(MAKE) $(MFLAGS) manta
	cd list-final; $(MAKE) $(MFLAGS) manta
	cd list-final-conv; $(MAKE) $(MFLAGS) manta
	cd list-normal; $(MAKE) $(MFLAGS) manta
	cd list-normal-conv; $(MAKE) $(MFLAGS) manta
	cd tree-final; $(MAKE) $(MFLAGS) manta
	cd tree-final-conv; $(MAKE) $(MFLAGS) manta
	cd tree-final-sun; $(MAKE) $(MFLAGS) manta
	cd object-array; $(MAKE) $(MFLAGS) manta	
	cd object-array-conv; $(MAKE) $(MFLAGS) manta
	cd int-array; $(MAKE) $(MFLAGS) manta	
	cd int-array-conv; $(MAKE) $(MFLAGS) manta
	cd dlist-final; $(MAKE) $(MFLAGS) manta
	cd dlist-final-conv; $(MAKE) $(MFLAGS) manta

clean:
	rm -f $(TRASH_FILES)
	cd array; $(MAKE) $(MFLAGS) clean	
	cd array-sun; $(MAKE) $(MFLAGS) clean	
	cd array-writeArray; $(MAKE) $(MFLAGS) clean	
	cd array-conv; $(MAKE) $(MFLAGS) clean
	cd array-conv-writeArray; $(MAKE) $(MFLAGS) clean
	cd list-final; $(MAKE) $(MFLAGS) clean
	cd list-final-conv; $(MAKE) $(MFLAGS) clean
	cd list-normal; $(MAKE) $(MFLAGS) clean
	cd list-normal-conv; $(MAKE) $(MFLAGS) clean
	cd tree-final; $(MAKE) $(MFLAGS) clean
	cd tree-final-conv; $(MAKE) $(MFLAGS) clean
	cd tree-final-sun; $(MAKE) $(MFLAGS) clean
	cd object-array; $(MAKE) $(MFLAGS) clean	
	cd object-array-conv; $(MAKE) $(MFLAGS) clean
	cd int-array; $(MAKE) $(MFLAGS) clean	
	cd int-array-conv; $(MAKE) $(MFLAGS) clean
	cd dlist-final; $(MAKE) $(MFLAGS) clean
	cd dlist-final-conv; $(MAKE) $(MFLAGS) clean
