SRC	 = RMI_init.java
SRC	+= i_BroadcastObject.java
SRC	+= BroadcastObject.java
SRC	+= i_Central.java
SRC	+= Central.java
SRC	+= Barrier.java

SRC	+= BroadcastSender.java
SRC	+= DoubleVector.java 
SRC	+= LEQ.java
SRC	+= Update.java

MAIN	 = Main.java

REMOTE	 = BroadcastObject.java
REMOTE	+= Central.java

SERIALIZABLE	 =

include ../../../config.mk

clean:
	rm -f $(TRASH_FILES) rmi_s*_BroadcastObject.java rmi_s*_Central.java
