/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_JavaMx_LinkManager */

#ifndef _Included_ibis_ipl_impl_mx_JavaMx_LinkManager
#define _Included_ibis_ipl_impl_mx_JavaMx_LinkManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_JavaMx_LinkManager
 * Method:    addLinks
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_00024LinkManager_addLinks
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
