/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_JavaMx */

#ifndef _Included_ibis_ipl_impl_mx_JavaMx
#define _Included_ibis_ipl_impl_mx_JavaMx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1init
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_finalize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1finalize
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_NewHandler
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1NewHandler
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_closeHandler
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1closeHandler
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_getMyNicId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1getMyNicId
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_getMyEndpointId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1getMyEndpointId
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_getNicId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1getNicId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_connect
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1connect
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_send
 * Signature: (Ljava/nio/ByteBuffer;IIJI)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1send
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_sendSynchronous
 * Signature: (Ljava/nio/ByteBuffer;IIJI)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1sendSynchronous
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_recv
 * Signature: (Ljava/nio/ByteBuffer;IJI)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1recv__Ljava_nio_ByteBuffer_2IJI
  (JNIEnv *, jclass, jobject, jint, jlong, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_recv
 * Signature: (Ljava/nio/ByteBuffer;IJJI)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1recv__Ljava_nio_ByteBuffer_2IJJI
  (JNIEnv *, jclass, jobject, jint, jlong, jlong, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_wait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1wait
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    jmx_test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_jmx_1test
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
