/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_JavaMx */

#ifndef _Included_ibis_ipl_impl_mx_JavaMx
#define _Included_ibis_ipl_impl_mx_JavaMx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_init
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    deInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_deInit
  (JNIEnv *, jclass);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    newHandler
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_newHandler
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    closeHandler
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_closeHandler
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    getMyNicId
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_JavaMx_getMyNicId
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    getMyEndpointId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_getMyEndpointId
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    getNicId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ibis_ipl_impl_mx_JavaMx_getNicId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    connect
 * Signature: (IIJII)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_connect__IIJII
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    connect
 * Signature: (IIJIIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_connect__IIJIIJ
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    send
 * Signature: (Ljava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_send
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    sendSynchronous
 * Signature: (Ljava/nio/ByteBuffer;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_sendSynchronous
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IIIJ)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_recv__Ljava_nio_ByteBuffer_2IIIJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    recv
 * Signature: (Ljava/nio/ByteBuffer;IIIJJ)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_recv__Ljava_nio_ByteBuffer_2IIIJJ
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    wait
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_wait__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    wait
 * Signature: (IIJ)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_wait__IIJ
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    test
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ibis_ipl_impl_mx_JavaMx_test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    cancel
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_cancel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx
 * Method:    wakeup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ibis_ipl_impl_mx_JavaMx_wakeup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
