/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_JavaMx_HandleManager */

#ifndef _Included_ibis_ipl_impl_mx_JavaMx_HandleManager
#define _Included_ibis_ipl_impl_mx_JavaMx_HandleManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_JavaMx_HandleManager
 * Method:    addHandles
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_00024HandleManager_addHandles
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
