/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ibis_ipl_impl_mx_JavaMx_HandleManager */

#ifndef _Included_ibis_ipl_impl_mx_JavaMx_HandleManager
#define _Included_ibis_ipl_impl_mx_JavaMx_HandleManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ibis_ipl_impl_mx_JavaMx_HandleManager
 * Method:    init
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_00024HandleManager_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ibis_ipl_impl_mx_JavaMx_HandleManager
 * Method:    addBlock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ibis_ipl_impl_mx_JavaMx_00024HandleManager_addBlock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
