java:
	cd Generic  && $(MAKE) $(MFLAGS) java
	cd Remote  && $(MAKE) $(MFLAGS) java
#	cd Remote2  && $(MAKE) $(MFLAGS) java
#	cd Remote3  && $(MAKE) $(MFLAGS) java
#	cd Remote4  && $(MAKE) $(MFLAGS) java

clean:
	cd Generic  && $(MAKE) $(MFLAGS) clean
	cd Remote  && $(MAKE) $(MFLAGS) clean
#	cd Remote2  && $(MAKE) $(MFLAGS) clean
#	cd Remote3  && $(MAKE) $(MFLAGS) clean
#	cd Remote4  && $(MAKE) $(MFLAGS) clean
