SRC	=
SRC	+= StoreOutputStream.java
SRC	+= StoreInputStream.java
SRC	+= StoreBuffer.java
SRC	+= DITree.java

MAIN = Main.java

SERIALIZABLE	=
SERIALIZABLE	+= DITree.java

include ../../../../../config.mk

clean:
	rm -f $(TRASH_FILES)
