SRC  = Body.java
SRC  = SendBody.java
SRC += BodyTree.java		    
SRC += BodyTreeNode.java			    
SRC += CenterOfMass.java		    
SRC += DasInfo.java	    
SRC += GlobalData.java		    
SRC += NodeID.java		    
SRC += OrbTree.java		    
SRC += Plummer.java
SRC += Processor.java    
SRC += ProcessorThread.java	    
SRC += Procs.java    
SRC += RandomNumber.java    
SRC += SetEssentialThread.java
SRC += vec3.java
SRC += MinMax.java

MAIN = BarnesHutt.java

REMOTE = ProcsImpl.java
REMOTE += ProcessorImpl.java

SERIALIZABLE = SendBody.java
SERIALIZABLE += Body.java
SERIALIZABLE += CenterOfMass.java
SERIALIZABLE += GlobalData.java
SERIALIZABLE += NodeID.java
SERIALIZABLE += vec3.java
SERIALIZABLE += MinMax.java

OUT=main

include ../../../config.mk

clean:
	rm -f $(TRASH_FILES) rmi_s*_ProcsImpl.java rmi_s*_ProcessorImpl.java
