package ibis.impl.net.bytes;

public interface Settings {

        /** 
         * Upper bound on the length of byte buffers generated by the <code>'byte'</code> driver.
         */
        // final int maxMtu = Integer.MAX_VALUE;
        final int maxMtu = 0;
}
