#!/usr/bin/perl

open(F, "configuration") or die "Can't open configuration input file: $!\n";

open(OUTFILE, "> /tmp/IBIS_TEST_BUILD/ibis/configuration") or die "Can't open configuration output file: $!\n";

while ($line = <F>) {
    @words = split("=", $line);

    if ($words[0] eq "IBIS_ROOT") {
	print OUTFILE "IBIS_ROOT=/tmp/IBIS_TEST_BUILD\n";
    } elsif ($words[0] eq "JAVA_ROOT") {
	print OUTFILE "JAVA_ROOT=/home/rob/contrib/IBMJava2-13\n";
    } elsif ($words[0] eq "JAVAC") {
	print OUTFILE "JAVAC=/home/rob/contrib/IBMJava2-13/bin/javac\n";
    } else {
	print OUTFILE $line;
    }
}

close OUTFILE;
