#!/usr/bin/perl -w
my $IBIS_TEST_DIR_PREFIX = $ENV{'IBIS_TEST_DIR_PREFIX'}||'/tmp';
my $INITIAL_IBIS_DIR 	 = $ENV{'IBIS_ROOT'};
my $IBIS_TEST_DIR    	 = $ARGV[0]||$ENV{'IBIS_TEST_DIR'}||'/${IBIS_TEST_DIR_PREFIX}/$ENV{USER}/IBIS_TEST_BUILD';

open(F, "${INITIAL_IBIS_DIR}/ibis/configuration") or die "Can't open configuration input file: $!\n";
open(OUTFILE, "> ${IBIS_TEST_DIR}/ibis/configuration") or die "Can't open configuration output file: $!\n";

while (my $line = <F>) {
    my @words = split("=", $line);

    if ($words[0] eq "IBIS_ROOT") {
	print OUTFILE "IBIS_ROOT=${IBIS_TEST_DIR}\n";
    } elsif ($words[0] eq "JAVA_ROOT") {
	print OUTFILE "JAVA_ROOT=/usr/local/ibm-java/IBMJava2-131\n";
    } elsif ($words[0] eq "JAVAC") {
	print OUTFILE "JAVAC=/usr/local/ibm-java/IBMJava2-131/bin/javac\n";
    } else {
	print OUTFILE $line;
    }
}

close OUTFILE;
