#!/bin/sh #emacs likes this :-)

#This script is the globusjob that is run by grun

#grun puts the lines
#
# #!/bin/sh
# APP_DIR=<dir>
# MODE=<master|slave>
# JOBID=<pid of grun>
#
#before this file

#This script takes care of the CLASSPATH and ibis.property.file settings

#The parameters to this script are given to java, see below


#import gridlab.conf

if [ -f /etc/gridlab.conf ]; then
	. /etc/gridlab.conf
fi

if [ ! -f .grun ]; then
	echo `pwd`/.grun not found at `hostname`, exiting...
	exit 1
fi

#common settings for this site are read from .grun
#This includes:
# - JAVA_HOME, the directory with the java 'environment'
# - JAR_PATH, the directory with the .jar files
#	          (all are included in the CLASSPATH)
# - JAVA_PARAMS, extra parameters for the java executable at this site
#                (this setting is optional)

#.grun must be included *after* /etc/gridlab.conf because JAVA_HOME is
#sometimes nicely defined there and .grun uses it for its JAR_PATH
. .grun

#handy variables
IBIS_ROOT=`pwd`/tmp$JOBID

CLASSPATH=$IBIS_ROOT/ibis/classlibs:$IBIS_ROOT:.
for i in $JAR_PATH/*.jar; do
	CLASSPATH=$CLASSPATH:$i
done

if [ "$MODE" = "master" ]; then
	#prepare the ibis directory
	(
	    cd $IBIS_ROOT
	    if [ ! -f ibis.tgz ]; then
		echo ibis.tgz not found, exiting...
		exit 1
    	    fi
	    gunzip ibis.tgz
	    tar xf ibis.tar
	    rm ibis.tar
	)
	#signal the slaves the master is ready
	touch grun${JOBID}_master_is_ready
elif [ "$MODE" = "slave" ]; then
	while [ ! -f grun${JOBID}_master_is_ready ]; do sleep 1; done
fi

cd $IBIS_ROOT/$APP_DIR

$JAVA_HOME/bin/java $JAVA_PARAMS -Dibis.property.file=$IBIS_ROOT/ibis/properties -Xbootclasspath:$CLASSPATH -classpath $CLASSPATH $*
