SRC=  LocalVariableGen.java
MAIN = 
OUT=

PACKAGE	= org.apache.bcel.generic

include ../../../../../config.mk

java:	java_local

java_local:	$(CLASS_FILES) $(MAIN_CLASS)

manta:

clean:
	rm -f $(TRASH_FILES) *.so *.a

distclean:	clean
