#!/bin/bash

# reserve="-reserve 748923"
# javaflags="-ip-map /home/rutger/myrinet-ip-map"

myrinet_N=1000000
tcp_N=10000
# tcp_N=100000

n=10

sers="ibis sun"
# sers="sun"

for (( i = 0; i < $n; i++ )) ; do

    ibises="panda net.gm"
    # ibises="panda"

    if true ; then
	for ibis in $ibises ; do
	    for ser in $sers ; do
		sh run-rpc $ibis $ser $myrinet_N 0 "$reserve" "$javaflags" ""
	    done
	done
    fi

    ibises="net.tcp_blk net.gen.tcp_blk tcp"
    # ibises="SUN"

    if true ; then
	for ibis in $ibises ; do
	    for (( j = 0; j < 5; j++ )); do
		for ser in $sers ; do
		    sh run-rpc $ibis $ser $tcp_N 0 "$reserve" "$javaflags" ""
		done
	    done
	done
    fi

done
