#!/bin/bash

reserve="-reserve 724368"
javaflags="-ip-map /home/rutger/myrinet-ip-map"

n=10

sers="ibis sun"
# sers="ibis sun"

for (( i = 0; i < $n; i++ )) ; do

    ibises="panda net.gm"
    # ibises="panda"

    if true ; then
	for ibis in $ibises ; do
	    for ser in $sers ; do
		sh run-rpc $ibis $ser 1000000 0 "$reserve" "$javaflags" ""
	    done
	done
    fi

    # ibises="net.tcp_blk net.gen.tcp_blk tcp"
    ibises="tcp net.bytes.gen.tcp_blk"

    if true ; then
	for ibis in $ibises ; do
	    for (( j = 0; j < 5; j++ )); do
		for ser in $sers ; do
		    sh run-rpc $ibis $ser 10000 0 "$reserve" "$javaflags" ""
		done
	    done
	done
    fi

done
