#! /bin/sh

directory=`pwd`

case $# in
0)	;;
1)	directory=$1
	;;
*)	echo Usage: $0 [ <subdirectory> ] 1>&2
	exit 1
	;;
esac

cd $directory

tempfile=list.$$
trap "rm -f $tempfile" 0 1 2 3 15
find . -name build.xml -print > $tempfile
for i in `cat $tempfile`
do
    dir=`dirname $i`
    echo "++++++++++++++++++ $dir +++++++++++++++++"
    ( cd $dir && ant clean build )
done
