#!/bin/bash

d=`dirname $0`
IBIS=`cd $d/.. ; pwd`
echo IBIS $IBIS

main=`cat run-args`
# options="22 -warmup 4"

reservation="724392"
t="15:0"

# reserve="-reserve $reservation"
timeout="-t $t"

nodes="2 4 8 16 24 32 40 48 56 64"
# nodes="32"
runs=10
# runs=1

sers="ibis sun"

ibises="tcp net.multi.bytes.gen.tcp_blk panda net.multi.gm net.gm"

sequential=0
parallel=1
options=""

while [ $# -gt 0 ] ; do
    qarg="'"$1"'"
# echo Now inspect argument $1 -- left $#
    case "$1" in
    -p)
	shift
	nodes="$1"
	;;
    -ibis)
	shift
	ibises="$1"
	;;
    -t)
	shift
	timeout="-t $1"
	;;
    -reserve)
	shift
	reservation="$1"
	reserve="-reserve $reservation"
	;;
    -x)
	shift
	runs="$1"
	;;
    -ser)
	shift
	sers="$1"
	;;
    -seq)
	sequential=1
	;;
    -no-seq)
	sequential=0
	;;
    -par)
	parallel=1
	;;
    -no-par)
	parallel=0
	;;
    -no-std)
	main=
	;;
    -jvm-opt)
	shift
	java_options="$java_options \"$1\""
	;;
    *)
	options="$options $1"
	;;
    esac
    shift
done

if [ "$options" != "" ] ; then
	main=
fi

prun_options="IBP_SEND_SYNC=0 $reserve $timeout"

preserve -long-list | grep $reservation

if [ $sequential -eq 1 ] ; then
    for ibis in $ibises ; do
	node=1
	for ser in $sers ; do
	    echo "ser=$ser node=$node ibis=$ibis"
	    prun $prun_options -pre-cleanup -v -1 -no-panda $IBIS/bin/run-das $node $java_options -Dibis.name=$ibis -Dibis.serialization=$ser -Dibis.worldmodel=closed $main $options
	done
    done
fi

if [ $parallel -eq 1 ] ; then
    for (( i = 0; i < $runs; i++ )) ; do
	for node in $nodes ; do
	    for ibis in $ibises ; do
		for ser in $sers ; do
		    echo "ser=$ser node=$node ibis=$ibis"
		    prun $prun_options -pre-cleanup -v -1 -no-panda $IBIS/bin/run-das $node $java_options -Dibis.name=$ibis -Dibis.serialization=$ser -Dibis.worldmodel=closed $main $options
		done
	    done
	done
    done
fi
