# SRC=  DowncallLatency.java

SRC	=
SRC	+= NullOutputStream.java
SRC	+= List.java

MAIN = Main.java

SERIALIZABLE =
SERIALIZABLE += List.java

include ../../../../../config.mk

clean:
	rm -f $(TRASH_FILES)
