SRC = myServer.java 
SRC += DasInfo.java 

REMOTE  = Test.java 

MAIN = Main.java
OUT=main

MP_MODE=Panda

include ../../../config.mk

java: $(CLASS_FILES) $(MAIN_CLASS)

manta: $(MAIN) $(O_FILES)

clean:
	rm -f $(TRASH_FILES) rmi_s*_Test.java







